# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(584, 383)
        self.tb = QtWidgets.QTextBrowser(Form)
        self.tb.setGeometry(QtCore.QRect(140, 90, 256, 192))
        self.tb.setObjectName("tb")
        for i in range(20):
            self.tb.append("hahaha")  # 在textbrower框中添加一行数据
            self.tb.moveCursor(self.tb.textCursor().End)  # 把滚动条下拉到尾部

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

